apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: muzakkirsaifi/weathear-app:v2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
